[package]
name = "fhre_demo"
version = "0.1.0"
edition = "2021"

[lib]
name = "fhre_demo"
path = "src/lib.rs"
crate-type = ["staticlib"]

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
lto = true
codegen-units = 1
opt-level = "z"

[features]
default = []
sim-opengl = ["fhre/sim-opengl"]
sim-opengl-egl = ["fhre/sim-opengl-egl"]

[dependencies]
fhre = { path = "../../../fhre/rust" }
