############################################################################
# apps/examples/fhre_demo/clang/Makefile
############################################################################

include $(APPDIR)/Make.defs

MODULE = $(CONFIG_EXAMPLES_FHRE_DEMO_CLANG)

include $(APPDIR)/Application.mk

