[package]
name = "fhre"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[lib]
name = "fhre"
path = "src/lib.rs"
crate-type = ["rlib"]

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
lto = true
codegen-units = 1
opt-level = "z"

[features]
default = []
sim-opengl = []
sim-opengl-egl = ["sim-opengl"]

[dependencies]
