############################################################################
# apps/examples/wing_demo/clang/Makefile
############################################################################

include $(APPDIR)/Make.defs

MODULE = $(CONFIG_EXAMPLES_WING_DEMO_CLANG)

include $(APPDIR)/Application.mk

