[package]
name = "wing_rs_demo"
version = "0.1.0"
edition = "2021"

[lib]
name = "wing_rs_demo"
path = "src/lib.rs"
crate-type = ["staticlib", "rlib"]

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
lto = true
codegen-units = 1
opt-level = 'z'

[dependencies]
fhre = { path = "../../../../apps/fhre/rust", default-features = false }
wing = { path = "../../../../apps/wing/rust", default-features = false }
libm = "0.2"

[features]
default = []
