############################################################################
# apps/fhre/clang/Makefile
############################################################################

include $(APPDIR)/Make.defs

MODULE = $(CONFIG_FHRE_CLANG)

include $(APPDIR)/Application.mk
