############################################################################
# apps/wing_old2/Makefile
############################################################################

# Archived prototype. No active build targets.

.PHONY: all context depend clean distclean install preconfig register

all context depend clean distclean install preconfig register:
