//! Sync System - Entity synchronization between Main World and Render World
//!
//! Synchronizes entities marked with SyncToRenderWorld between Main World and Render World.
//! This runs before the Extract phase.
//!
//! # Observer Mechanism
//!
//! Entity sync is triggered automatically via Observer pattern:
//! - `insert_component<SyncToRenderWorld>` → adds `EntityRecord::Added` to PendingSyncEntity
//! - `remove_component<SyncToRenderWorld>` → adds `EntityRecord::Removed` to PendingSyncEntity
//! - `despawn` entity with `RenderEntity` → adds `EntityRecord::Removed` to PendingSyncEntity

use crate::main_world::MainWorld;
use crate::render_world::RenderWorld;
use crate::sync::sync_markers::RenderEntity;
use crate::sync::pending_sync::{PendingSyncEntity, EntityRecord};
use alloc::vec::Vec;

/// System that synchronizes entities between Main World and Render World
///
/// This should run in the Sync schedule, before ExtractSchedule.
/// Processes all pending sync records generated by the Observer mechanism.
pub fn entity_sync_system(main_world: &mut MainWorld, render_world: &mut RenderWorld) {
    let records: Vec<_> = {
        let pending = main_world.resources().get::<PendingSyncEntity>();
        match pending {
            Some(pending) => pending.records.clone(),
            None => return,
        }
    };
    
    for record in records {
        match record {
            EntityRecord::Added(main_entity) => {
                sync_added_entity(main_world, render_world, main_entity);
            }
            EntityRecord::Removed(render_entity) => {
                sync_removed_entity(render_world, render_entity);
            }
        }
    }
    
    if let Some(pending) = main_world.resources_mut().get_mut::<PendingSyncEntity>() {
        pending.clear();
    }
}

/// Handle entity added to Main World with SyncToRenderWorld
fn sync_added_entity(
    main_world: &mut MainWorld,
    render_world: &mut RenderWorld,
    main_entity: crate::Entity,
) {
    if main_world.get_component::<RenderEntity>(main_entity).is_some() {
        return;
    }
    
    let render_entity = render_world.spawn_synced(main_entity);
    main_world.insert_component(main_entity, RenderEntity(render_entity));
}

/// Handle entity removed from Main World or SyncToRenderWorld removed
fn sync_removed_entity(
    render_world: &mut RenderWorld,
    render_entity: RenderEntity,
) {
    render_world.despawn(render_entity.0);
}
