############################################################################
# apps/fhre/Makefile
############################################################################

MENUDESC = "Feather Hybrid Render Engine (FHRE)"

include $(APPDIR)/Directory.mk
