############################################################################
# apps/wing/surface_demo/Makefile
############################################################################

include $(APPDIR)/Make.defs

PROGNAME  = $(CONFIG_WING_SURFACE_DEMO_PROGNAME)
PRIORITY  = $(CONFIG_WING_SURFACE_DEMO_PRIORITY)
STACKSIZE = $(CONFIG_WING_SURFACE_DEMO_STACKSIZE)
MODULE    = $(CONFIG_WING_SURFACE_DEMO)

MAINSRC = surface_demo_main.c

include $(APPDIR)/Application.mk
