############################################################################
# apps/wing/Makefile
############################################################################

include $(APPDIR)/Make.defs

SUBDIRS = rust

include $(APPDIR)/Directory.mk
