############################################################################
# apps/wing/clang/Makefile
############################################################################

include $(APPDIR)/Make.defs

MODULE = $(CONFIG_WING_CLANG)

include $(APPDIR)/Application.mk

